"""
Hand-curated context: chokepoints, the 2025–26 event timeline, a dated market snapshot,
and major energy infrastructure. Every figure carries a source; update AS_OF when editing.
"""

AS_OF = "2026-09-23"

SRC = {
    "eia_wotc": ("EIA, World Oil Transit Chokepoints (updated 3 Mar 2026)",
                 "https://www.eia.gov/international/content/analysis/special_topics/World_Oil_Transit_Chokepoints"),
    "eia_press_jun26": ("EIA press release, 9 Jun 2026",
                        "https://www.eia.gov/pressroom/releases/press589.php"),
    "eia_steo": ("EIA Short-Term Energy Outlook, Sep 2026", "https://www.eia.gov/outlooks/steo/"),
    "eia_tie_2q26": ("EIA Today in Energy: petroleum markets in 2Q26",
                     "https://www.eia.gov/todayinenergy/detail.php?id=67865"),
    "eia_uae": ("EIA Today in Energy: UAE exit from OPEC+", "https://www.eia.gov/todayinenergy/detail.php?id=67804"),
    "iea_omr_sep26": ("IEA Oil Market Report, Sep 2026", "https://www.iea.org/reports/oil-market-report-september-2026"),
    "iea_omr_aug26": ("IEA Oil Market Report, Aug 2026 (via Hydrocarbon Processing)",
                      "https://www.hydrocarbonprocessing.com/news/2026/08/iea-global-2026-oil-supply-shortfall-to-deepen-as-hormuz-reopening-remains-elusive/"),
    "wiki_hormuz": ("Wikipedia: 2026 Strait of Hormuz campaign", "https://en.wikipedia.org/wiki/2026_Strait_of_Hormuz_campaign"),
    "wiki_fuel": ("Wikipedia: 2026 Iran war fuel crisis", "https://en.wikipedia.org/wiki/2026_Iran_war_fuel_crisis"),
    "wiki_chrono": ("Wikipedia: 2026–2028 world oil market chronology",
                    "https://en.wikipedia.org/wiki/2026%E2%80%932028_world_oil_market_chronology"),
    "euronews_lng": ("Euronews, 8 Sep 2026: Qatar and UAE test ways to keep LNG moving",
                     "https://www.euronews.com/business/2026/09/08/six-months-into-hormuz-blockade-qatar-and-uae-test-ways-to-keep-lng-moving"),
    "rte_qatar": ("RTÉ, 4 Mar 2026: Qatar shuts gas liquefaction", "https://www.rte.ie/news/business/2026/0304/1561653-qatar-shutdown/"),
    "fortune_petroline": ("Fortune, 28 Mar 2026: Saudi pipeline hits 7 mb/d",
                          "https://fortune.com/2026/03/28/saudi-arabia-east-west-oil-pipeline-strait-hormuz-bypass-7-million-barrels-yanbu-red-sea/"),
    "usnews_petroline": ("Reuters via US News, 22 Sep 2026: Saudi Arabia restarts East-West pipeline",
                         "https://www.usnews.com/news/world/articles/2026-09-22/saudi-arabia-restarts-east-west-oil-pipeline-to-resume-exports-from-yanbu-sources-say"),
    "aj_houthis": ("Al Jazeera, 13 Sep 2026: Houthis seize Bab al-Mandeb strait",
                   "https://www.aljazeera.com/economy/2026/9/13/red-sea-nations-watch-as-houthis-seize-bab-al-mandeb-strait"),
    "cnn_talks": ("CNN, 13 Sep 2026: Iran–Gulf talks on reopening Hormuz postponed",
                  "https://www.cnn.com/2026/09/13/politics/iran-gulf-countries-strait-of-hormuz"),
    "aj_mou": ("Al Jazeera, 9 Jul 2026: what happened since the US–Iran MoU",
               "https://www.aljazeera.com/news/2026/7/9/strait-of-hormuz-what-has-happened-since-the-us-iran-mou-on-june-17"),
    "cnbc_uae": ("CNBC, 28 Apr 2026: UAE to leave OPEC", "https://www.cnbc.com/2026/04/28/uae-opec-oil-iran.html"),
    "cnn_transit": ("CNN, 1 Jan 2025: Ukraine ends Russian gas transit",
                    "https://edition.cnn.com/2025/01/01/business/ukraine-russia-gas-eu-halted-hnk-intl"),
    "sc_sanctions": ("Sullivan & Cromwell: US sanctions Rosneft and Lukoil (22 Oct 2025)",
                     "https://www.sullcrom.com/insights/memo/2025/October/United-States-Sanctions-Significant-Russian-Oil-Companies-Rosneft-Lukoil"),
    "aj_kirkuk": ("Al Jazeera, 27 Sep 2025: Iraq resumes Kurdish oil exports to Türkiye",
                  "https://www.aljazeera.com/news/2025/9/27/iraq-resumes-kurdish-oil-exports-to-turkiye-after-two-and-a-half-year-halt"),
    "te": ("Trading Economics (commodity quotes)", "https://tradingeconomics.com/commodities"),
    "portwatch": ("IMF PortWatch — daily chokepoint transits", "https://portwatch.imf.org/"),
    "ei": ("Energy Institute, Statistical Review of World Energy 2026", "https://www.energyinst.org/statistical-review"),
}


def src(*keys):
    return [{"label": SRC[k][0], "url": SRC[k][1]} for k in keys]


# ------------------------------------------------------------------------------------------
# Chokepoints. EIA volumes: million b/d (total oil, crude & condensate, products), LNG in Bcf/d.
# Years: calendar 2020–2024 and 1H2025 ("2025h1"); Panama uses fiscal years.
# ------------------------------------------------------------------------------------------
CHOKEPOINTS = [
    {
        "id": "hormuz", "name": "Strait of Hormuz", "coords": [56.45, 26.55], "portwatch": "chokepoint6",
        "status": "closed", "status_label": "Effectively closed",
        "status_note": "Closed to most commercial traffic since 2 Mar 2026 after US–Israeli strikes on Iran. "
                       "IMF PortWatch logged 0–8 transits a day in September 2026 against roughly 100 a day in 2025. "
                       "The US has blockaded Iranian ports since April; a June truce collapsed in July.",
        "oil": {"2020": 19.2, "2021": 19.7, "2022": 21.9, "2023": 21.8, "2024": 20.7, "2025h1": 20.9},
        "crude": {"2024": 14.6, "2025h1": 14.7}, "products": {"2024": 6.1, "2025h1": 6.1},
        "lng": {"2020": 10.7, "2021": 10.8, "2022": 11.0, "2023": 10.6, "2024": 10.5, "2025h1": 11.4},
        "share_note": "≈20% of world petroleum-liquids consumption and >20% of global LNG trade (1H25).",
        "bypass": [
            {"name": "Saudi East–West pipeline (Abqaiq → Yanbu)", "capacity_mbd": 7.0,
             "note": "Record 7 mb/d in 1Q26; shut by drone strikes 13 Sep 2026, restarted 22 Sep."},
            {"name": "UAE ADCOP (Habshan → Fujairah)", "capacity_mbd": 1.5,
             "note": "Second line fast-tracked for 2027."},
            {"name": "Iraq Kirkuk → Ceyhan (Türkiye)", "capacity_mbd": 0.3,
             "note": "Restarted 27 Sep 2025 after a 2½-year halt; nameplate far higher."},
        ],
        "sources": src("eia_wotc", "wiki_hormuz", "portwatch", "cnn_talks"),
    },
    {
        "id": "malacca", "name": "Strait of Malacca", "coords": [100.5, 3.0], "portwatch": "chokepoint5",
        "status": "open", "status_label": "Open",
        "status_note": "Open. Volumes are depressed because Gulf crude bound for East Asia is stranded behind Hormuz.",
        "oil": {"2020": 22.8, "2021": 22.1, "2022": 23.0, "2023": 24.0, "2024": 22.5, "2025h1": 23.2},
        "crude": {"2024": 15.9, "2025h1": 16.6}, "products": {"2024": 6.6, "2025h1": 6.5},
        "lng": {"2020": 7.4, "2021": 8.9, "2022": 8.3, "2023": 9.4, "2024": 10.1, "2025h1": 9.2},
        "share_note": "Largest oil chokepoint: ≈29% of seaborne oil (1H25). China takes ~48% of volumes.",
        "sources": src("eia_wotc", "portwatch"),
    },
    {
        "id": "suez", "name": "Suez Canal & SUMED", "coords": [32.4, 30.4], "portwatch": "chokepoint1",
        "status": "restricted", "status_label": "Reduced",
        "status_note": "Open, but volumes remain about half of 2023 levels because of the Red Sea security crisis.",
        "oil": {"2020": 5.4, "2021": 5.2, "2022": 7.3, "2023": 8.8, "2024": 4.8, "2025h1": 4.9},
        "crude": {"2024": 3.0, "2025h1": 2.8}, "products": {"2024": 1.7, "2025h1": 2.1},
        "lng": {"2020": 3.8, "2021": 4.7, "2022": 4.6, "2023": 4.1, "2024": 0.5, "2025h1": 0.9},
        "share_note": "SUMED pipeline capacity 2.5 mb/d (Ain Sukhna → Sidi Kerir).",
        "sources": src("eia_wotc", "portwatch"),
    },
    {
        "id": "bab_el_mandeb", "name": "Bab el-Mandeb", "coords": [43.35, 12.6], "portwatch": "chokepoint4",
        "status": "high_risk", "status_label": "High risk",
        "status_note": "By September 2026 the Houthis held Yemen's whole Red Sea coast, including Perim island "
                       "at the strait. They have attacked Saudi-linked shipping. LNG carriers have avoided "
                       "the route entirely since 2024.",
        "oil": {"2020": 5.7, "2021": 6.0, "2022": 8.0, "2023": 9.3, "2024": 4.1, "2025h1": 4.2},
        "crude": {"2024": 2.7, "2025h1": 2.4}, "products": {"2024": 1.4, "2025h1": 1.8},
        "lng": {"2020": 3.8, "2021": 4.7, "2022": 4.6, "2023": 4.2, "2024": 0.0, "2025h1": 0.0},
        "share_note": "Down ~55% from 2023; flows rerouted around the Cape of Good Hope.",
        "sources": src("eia_wotc", "aj_houthis", "portwatch"),
    },
    {
        "id": "cape_good_hope", "name": "Cape of Good Hope", "coords": [18.3, -35.3], "portwatch": "chokepoint7",
        "status": "open", "status_label": "Open (diversion route)",
        "status_note": "Not a chokepoint, but it has become the main detour for Atlantic–Asia trade since late 2023.",
        "oil": {"2020": 7.9, "2021": 7.2, "2022": 6.1, "2023": 6.2, "2024": 9.3, "2025h1": 9.1},
        "crude": {"2024": 5.8, "2025h1": 6.1}, "products": {"2024": 3.4, "2025h1": 2.9},
        "lng": {"2020": 3.5, "2021": 3.3, "2022": 1.5, "2023": 2.1, "2024": 7.8, "2025h1": 5.7},
        "share_note": "≈11% of seaborne oil (1H25).",
        "sources": src("eia_wotc", "portwatch"),
    },
    {
        "id": "bosporus", "name": "Turkish Straits", "coords": [29.05, 41.1], "portwatch": "chokepoint3",
        "status": "open", "status_label": "Open",
        "status_note": "Open. Kazakh CPC crude is the largest flow. LNG is barred from the Bosporus.",
        "oil": {"2020": 2.9, "2021": 3.0, "2022": 2.9, "2023": 3.3, "2024": 3.3, "2025h1": 3.3},
        "crude": {"2024": 1.9, "2025h1": 2.1}, "products": {"2024": 1.4, "2025h1": 1.3},
        "lng": {"2024": 0.0, "2025h1": 0.0},
        "share_note": "Bosporus figures; the Dardanelles carried 3.7 mb/d in 1H25.",
        "sources": src("eia_wotc", "portwatch"),
    },
    {
        "id": "danish_straits", "name": "Danish Straits", "coords": [10.95, 55.4], "portwatch": "chokepoint10",
        "status": "open", "status_label": "Open",
        "status_note": "Open. This is the main outlet for Russian Baltic crude and products.",
        "oil": {"2020": 3.1, "2021": 3.1, "2022": 4.2, "2023": 5.0, "2024": 4.9, "2025h1": 4.9},
        "crude": {"2024": 2.7, "2025h1": 2.7}, "products": {"2024": 2.1, "2025h1": 2.2},
        "lng": {"2020": 0.5, "2021": 0.5, "2022": 1.1, "2023": 1.4, "2024": 1.4, "2025h1": 1.6},
        "share_note": "≈6% of seaborne oil. PortWatch series shown is the Øresund.",
        "sources": src("eia_wotc", "portwatch"),
    },
    {
        "id": "panama", "name": "Panama Canal", "coords": [-79.7, 9.1], "portwatch": "chokepoint2",
        "status": "open", "status_label": "Open",
        "status_note": "Open, and water levels have recovered from the 2023–24 drought. Mostly carries US refined "
                       "products and LPG; LNG has largely moved to the Cape route.",
        "oil": {"2020": 1.7, "2021": 1.8, "2022": 2.2, "2023": 2.2, "2024": 2.0, "2025": 2.3},
        "crude": {"2024": 0.1, "2025": 0.1}, "products": {"2024": 2.0, "2025": 2.2},
        "lng": {"2021": 2.5, "2025": 0.3},
        "share_note": "Fiscal years (Oct–Sep). ≈3% of seaborne oil.",
        "sources": src("eia_wotc", "portwatch"),
    },
    {
        "id": "gibraltar", "name": "Strait of Gibraltar", "coords": [-5.6, 35.96], "portwatch": "chokepoint8",
        "status": "open", "status_label": "Open", "status_note": "Open.",
        "sources": src("portwatch"),
    },
    {
        "id": "taiwan_strait", "name": "Taiwan Strait", "coords": [119.6, 24.4], "portwatch": "chokepoint11",
        "status": "open", "status_label": "Open", "status_note": "Open.",
        "sources": src("portwatch"),
    },
]

# Other PortWatch chokepoints we chart but do not describe in detail.
PORTWATCH_EXTRA = {
    "chokepoint9": "Dover Strait", "chokepoint12": "Korea Strait", "chokepoint15": "Lombok Strait",
    "chokepoint20": "Makassar Strait", "chokepoint14": "Luzon Strait",
}

# ------------------------------------------------------------------------------------------
# Timeline
# ------------------------------------------------------------------------------------------
EVENTS = [
    {"date": "2025-01-01", "tag": "gas", "title": "Russian gas transit through Ukraine ends",
     "body": "The Gazprom–Naftogaz transit contract expired. It had carried about half of Russia's remaining "
             "pipeline gas to the EU; TurkStream is now the only direct route.", "sources": src("cnn_transit")},
    {"date": "2025-09-27", "tag": "oil", "title": "Kirkuk–Ceyhan pipeline restarts",
     "body": "Iraqi Kurdistan crude resumed flowing to Türkiye's Ceyhan terminal at about 0.24 mb/d after a "
             "2½-year halt.", "sources": src("aj_kirkuk")},
    {"date": "2025-10-22", "tag": "sanctions", "title": "US sanctions Rosneft and Lukoil",
     "body": "OFAC blocked Russia's two largest oil producers, which account for about 55% of Russian output. The UK and EU took parallel measures.",
     "sources": src("sc_sanctions")},
    {"date": "2026-02-28", "tag": "conflict", "title": "US–Israeli strikes on Iran; Hormuz closed",
     "body": "The Islamic Revolutionary Guard Corps (IRGC) warned that no ship may pass the Strait of Hormuz, and commercial traffic collapsed within days.",
     "sources": src("wiki_hormuz")},
    {"date": "2026-03-02", "tag": "lng", "title": "Qatar halts LNG production",
     "body": "QatarEnergy shut Ras Laffan (~77 Mtpa, about 20% of world LNG) after Iranian strikes. The TTF gas "
             "benchmark rose more than 25% intraday and Asian JKM about 39%.", "sources": src("rte_qatar", "wiki_fuel")},
    {"date": "2026-03-18", "tag": "lng", "title": "Missiles damage Ras Laffan trains",
     "body": "Two LNG trains (12.8 Mtpa, ~17% of Qatar's capacity) were damaged; QatarEnergy estimates repairs "
             "will take years.", "sources": src("wiki_fuel")},
    {"date": "2026-03-28", "tag": "oil", "title": "Saudi East–West pipeline at a record 7 mb/d",
     "body": "Aramco maxed out the Petroline to Yanbu on the Red Sea; crude loadings there reached about 5 mb/d.",
     "sources": src("fortune_petroline")},
    {"date": "2026-04-13", "tag": "conflict", "title": "US naval blockade of Iranian ports",
     "body": "The blockade followed the failure of the Islamabad talks and was confirmed on 15 April.", "sources": src("wiki_hormuz")},
    {"date": "2026-04-28", "tag": "opec", "title": "UAE announces exit from OPEC and OPEC+",
     "body": "The exit took effect on 1 May 2026, ending 59 years of membership.", "sources": src("cnbc_uae", "eia_uae")},
    {"date": "2026-04-30", "tag": "price", "title": "Brent touches $126",
     "body": "An intraday four-year high, reached after threats of a wider blockade.", "sources": src("wiki_chrono")},
    {"date": "2026-06-09", "tag": "oil", "title": "Middle East output down by more than 11 mb/d",
     "body": "EIA estimated that OECD inventories would fall to their lowest level since 2003.",
     "sources": src("eia_press_jun26")},
    {"date": "2026-06-17", "tag": "conflict", "title": "US–Iran memorandum signed",
     "body": "Tankers briefly transited Hormuz and Brent fell to $73.74 by 24 June.", "sources": src("aj_mou", "wiki_chrono")},
    {"date": "2026-07-08", "tag": "conflict", "title": "Truce collapses; blockade reinstated",
     "body": "Attacks on commercial ships ended the interim ceasefire, and the US reimposed its blockade on 14–15 July.",
     "sources": src("wiki_hormuz", "aj_mou")},
    {"date": "2026-08-25", "tag": "conflict", "title": "More than 100 mines cleared from Hormuz lanes",
     "body": "The US Navy and contractors reported clearing the traffic separation scheme, though transits "
             "stayed near zero.", "sources": src("wiki_hormuz")},
    {"date": "2026-09-08", "tag": "lng", "title": "Qatar: 18 LNG cargoes in six months",
     "body": "That compares with 509 in the same period a year earlier. Non-Gulf supply offset about 75% of the loss.",
     "sources": src("euronews_lng")},
    {"date": "2026-09-09", "tag": "oil", "title": "EIA: global stocks down 400 million barrels",
     "body": "Brent averaged $91 in August. EIA expects Middle East output to stay below pre-war levels until 2Q27.",
     "sources": src("eia_steo")},
    {"date": "2026-09-11", "tag": "oil", "title": "IEA: 2026 supply down 5.7 mb/d",
     "body": "World supply is forecast at 100.7 mb/d, and demand is expected to fall by 2.5 mb/d this year. Russian product "
             "exports are near a halt after Ukrainian strikes on refineries.", "sources": src("iea_omr_sep26")},
    {"date": "2026-09-13", "tag": "conflict", "title": "Drones shut the East–West pipeline; Houthis take Perim",
     "body": "Saudi loadings at Yanbu stopped. The Houthis completed their takeover of Yemen's Red Sea coast at "
             "Bab el-Mandeb.", "sources": src("aj_houthis", "usnews_petroline")},
    {"date": "2026-09-22", "tag": "oil", "title": "Saudi Arabia restarts the East–West pipeline",
     "body": "Exports from Yanbu are set to resume. Brent is trading near $100 on hopes of Hormuz talks.",
     "sources": src("usnews_petroline", "te")},
]

# ------------------------------------------------------------------------------------------
# Market snapshot (spot / front-month) — dated. Annual averages come from EI.
# ------------------------------------------------------------------------------------------
MARKET = [
    {"id": "brent", "label": "Brent", "value": 99.60, "unit": "$/bbl", "date": "2026-09-23", "annual_key": "brent"},
    {"id": "wti", "label": "WTI", "value": 90.16, "unit": "$/bbl", "date": "2026-09-23", "annual_key": "wti"},
    {"id": "ttf", "label": "TTF (Europe gas)", "value": 73.68, "unit": "€/MWh", "date": "2026-09-23",
     "annual_key": "ttf", "annual_unit": "$/MMBtu"},
    {"id": "jkm", "label": "JKM (Asia LNG)", "value": 26.05, "unit": "$/MMBtu", "date": "2026-09-22", "annual_key": "jkm"},
    {"id": "henry_hub", "label": "Henry Hub (US gas)", "value": 3.01, "unit": "$/MMBtu", "date": "2026-09-23",
     "annual_key": "henry_hub"},
    {"id": "coal", "label": "Newcastle coal", "value": 145.40, "unit": "$/t", "date": "2026-09-22",
     "annual_key": "coal_australia"},
]
MARKET_SOURCE = src("te")

# ------------------------------------------------------------------------------------------
# Infrastructure (schematic routes — for orientation, not engineering accuracy)
# ------------------------------------------------------------------------------------------
PIPELINES = [
    # --- oil ---
    {"id": "petroline", "name": "East–West (Petroline)", "commodity": "oil", "capacity": "7 mb/d",
     "status": "disrupted", "note": "Hormuz bypass; drone strikes 13 Sep 2026, restarted 22 Sep.",
     "path": [[49.67, 25.93], [46.7, 24.7], [42.5, 24.3], [38.06, 24.09]]},
    {"id": "adcop", "name": "ADCOP (Habshan–Fujairah)", "commodity": "oil", "capacity": "1.5 mb/d",
     "status": "operating", "note": "Hormuz bypass to the Gulf of Oman.",
     "path": [[53.7, 23.8], [55.1, 24.3], [56.35, 25.15]]},
    {"id": "kirkuk_ceyhan", "name": "Kirkuk–Ceyhan", "commodity": "oil", "capacity": "1.5 mb/d nameplate",
     "status": "operating", "note": "Restarted Sep 2025 at ~0.2 mb/d.",
     "path": [[44.4, 35.47], [42.9, 36.9], [40.2, 37.1], [37.5, 37.0], [35.87, 36.88]]},
    {"id": "goreh_jask", "name": "Goreh–Jask", "commodity": "oil", "capacity": "≈0.3 mb/d used",
     "status": "disrupted", "note": "Iran's Hormuz bypass; limited throughput.",
     "path": [[50.6, 29.9], [52.5, 28.6], [55.4, 26.9], [57.77, 25.64]]},
    {"id": "sumed", "name": "SUMED", "commodity": "oil", "capacity": "2.5 mb/d", "status": "operating",
     "path": [[32.35, 29.6], [31.3, 30.3], [29.6, 31.1]]},
    {"id": "btc", "name": "Baku–Tbilisi–Ceyhan", "commodity": "oil", "capacity": "1.2 mb/d", "status": "operating",
     "path": [[49.5, 40.2], [46.5, 41.2], [44.8, 41.7], [42.7, 41.4], [40.7, 39.9], [38.5, 38.3], [35.87, 36.88]]},
    {"id": "cpc", "name": "Caspian Pipeline Consortium", "commodity": "oil", "capacity": "1.5 mb/d", "status": "operating",
     "path": [[53.4, 46.1], [47.9, 46.4], [44.3, 45.7], [41.0, 45.3], [37.8, 44.7]]},
    {"id": "druzhba", "name": "Druzhba (southern leg)", "commodity": "oil", "capacity": "≈0.3 mb/d used",
     "status": "operating", "note": "Supplies Hungary and Slovakia; repeatedly hit by strikes.",
     "path": [[52.3, 54.9], [44.0, 54.2], [36.0, 53.2], [29.3, 52.0], [25.0, 50.5], [22.3, 48.6], [18.9, 47.3], [17.1, 48.1]]},
    {"id": "espo", "name": "ESPO (with China spur)", "commodity": "oil", "capacity": "1.6 mb/d", "status": "operating",
     "path": [[98.0, 55.9], [108.0, 56.8], [116.0, 56.0], [123.9, 54.0], [128.5, 50.0], [131.5, 46.0], [132.9, 42.8]]},
    {"id": "espo_china", "name": "ESPO spur (Skovorodino–Daqing)", "commodity": "oil", "capacity": "0.6 mb/d",
     "status": "operating", "path": [[123.9, 54.0], [122.5, 53.0], [124.2, 49.5], [125.0, 46.6]]},
    {"id": "kaz_china", "name": "Kazakhstan–China", "commodity": "oil", "capacity": "0.4 mb/d", "status": "operating",
     "path": [[57.1, 50.3], [66.9, 48.0], [71.6, 48.7], [78.0, 46.5], [82.6, 45.2], [84.9, 44.3]]},
    {"id": "enbridge", "name": "Enbridge Mainline", "commodity": "oil", "capacity": "3.2 mb/d", "status": "operating",
     "path": [[-113.5, 53.5], [-104.6, 50.4], [-97.1, 49.9], [-92.1, 46.7], [-87.5, 43.3], [-82.4, 43.0]]},
    {"id": "keystone", "name": "Keystone", "commodity": "oil", "capacity": "0.62 mb/d", "status": "operating",
     "path": [[-111.4, 52.7], [-104.0, 49.0], [-97.4, 42.7], [-96.8, 36.0], [-95.4, 29.7]]},
    {"id": "tmx", "name": "Trans Mountain (TMX)", "commodity": "oil", "capacity": "0.89 mb/d", "status": "operating",
     "note": "Online May 2024; opened Asian markets to Canadian crude.",
     "path": [[-113.5, 53.5], [-118.3, 53.4], [-120.3, 50.7], [-122.95, 49.29]]},
    {"id": "chad_cameroon", "name": "Chad–Cameroon", "commodity": "oil", "capacity": "0.25 mb/d", "status": "operating",
     "path": [[16.8, 8.7], [14.5, 6.8], [11.8, 4.0], [9.9, 2.95]]},
    {"id": "niger_benin", "name": "Niger–Benin", "commodity": "oil", "capacity": "0.09 mb/d", "status": "operating",
     "path": [[12.5, 16.0], [8.0, 13.8], [3.4, 11.9], [2.6, 6.4]]},
    {"id": "myanmar_china_oil", "name": "Myanmar–China (oil & gas)", "commodity": "oil", "capacity": "0.44 mb/d",
     "status": "operating", "path": [[93.55, 19.43], [96.1, 21.9], [98.0, 24.0], [102.7, 25.0]]},
    {"id": "tal", "name": "Transalpine (TAL)", "commodity": "oil", "capacity": "0.8 mb/d", "status": "operating",
     "path": [[13.8, 45.65], [12.9, 47.3], [11.4, 48.8]]},
    {"id": "eacop", "name": "East African Crude Oil Pipeline", "commodity": "oil", "capacity": "0.25 mb/d",
     "status": "construction", "path": [[31.35, 1.43], [32.6, -2.5], [35.7, -5.0], [39.1, -5.07]]},
    # --- gas ---
    {"id": "power_of_siberia", "name": "Power of Siberia", "commodity": "gas", "capacity": "38 bcm/y",
     "status": "operating", "path": [[111.0, 60.5], [119.0, 56.5], [127.5, 50.3], [126.5, 45.8], [121.5, 41.0]]},
    {"id": "power_of_siberia_2", "name": "Power of Siberia 2 (planned)", "commodity": "gas", "capacity": "50 bcm/y",
     "status": "planned", "path": [[75.0, 67.0], [86.0, 56.0], [96.0, 51.5], [106.9, 47.9], [111.9, 43.6], [116.4, 39.9]]},
    {"id": "cagp", "name": "Central Asia–China", "commodity": "gas", "capacity": "55 bcm/y", "status": "operating",
     "path": [[61.7, 37.3], [64.4, 39.8], [69.3, 41.3], [72.0, 43.3], [80.4, 44.2], [87.6, 43.8]]},
    {"id": "turkstream", "name": "TurkStream", "commodity": "gas", "capacity": "31.5 bcm/y", "status": "operating",
     "note": "Only remaining direct route for Russian pipeline gas to the EU.",
     "path": [[37.3, 44.9], [33.5, 43.3], [30.0, 42.2], [28.1, 41.6], [26.9, 42.3], [23.6, 43.7], [21.0, 45.3], [19.9, 46.2]]},
    {"id": "blue_stream", "name": "Blue Stream", "commodity": "gas", "capacity": "16 bcm/y", "status": "operating",
     "path": [[38.7, 44.3], [37.3, 42.8], [36.3, 41.3], [32.8, 39.9]]},
    {"id": "nord_stream", "name": "Nord Stream 1 & 2", "commodity": "gas", "capacity": "110 bcm/y",
     "status": "halted", "note": "Out of service since the September 2022 sabotage.",
     "path": [[28.6, 60.6], [24.0, 59.8], [20.0, 57.5], [16.0, 55.4], [13.65, 54.14]]},
    {"id": "ukraine_transit", "name": "Ukraine transit (Brotherhood)", "commodity": "gas", "capacity": "40 bcm/y used 2024",
     "status": "halted", "note": "Ended 1 Jan 2025.",
     "path": [[35.4, 51.2], [31.0, 50.4], [26.0, 49.5], [22.2, 48.6]]},
    {"id": "southern_gas_corridor", "name": "Southern Gas Corridor (SCP–TANAP–TAP)", "commodity": "gas",
     "capacity": "≈24 bcm/y", "status": "operating",
     "path": [[49.5, 40.2], [44.8, 41.7], [42.0, 40.6], [37.0, 39.7], [32.0, 40.2], [28.0, 41.0], [26.3, 41.0],
              [23.0, 40.9], [20.5, 40.9], [18.5, 40.27]]},
    {"id": "norway_continental", "name": "Norway → Continent (Europipe/Norpipe/Franpipe/Zeepipe)", "commodity": "gas",
     "capacity": "≈90 bcm/y", "status": "operating",
     "path": [[3.0, 60.0], [3.2, 57.5], [4.5, 55.5], [6.2, 54.2], [7.3, 53.6]]},
    {"id": "langeled", "name": "Langeled / Vesterled (Norway → UK)", "commodity": "gas", "capacity": "≈38 bcm/y",
     "status": "operating", "path": [[6.9, 62.8], [3.0, 60.5], [0.5, 56.5], [0.1, 53.65]]},
    {"id": "baltic_pipe", "name": "Baltic Pipe", "commodity": "gas", "capacity": "10 bcm/y", "status": "operating",
     "path": [[3.2, 57.5], [8.2, 55.9], [12.0, 55.3], [15.1, 54.1]]},
    {"id": "transmed", "name": "TransMed (Enrico Mattei)", "commodity": "gas", "capacity": "33 bcm/y", "status": "operating",
     "path": [[3.3, 32.9], [8.3, 34.5], [10.9, 36.9], [12.6, 37.65], [14.5, 40.5], [12.5, 42.5]]},
    {"id": "medgaz", "name": "Medgaz", "commodity": "gas", "capacity": "10.5 bcm/y", "status": "operating",
     "path": [[3.3, 32.9], [0.6, 34.6], [-1.4, 35.3], [-2.4, 36.8]]},
    {"id": "greenstream", "name": "Greenstream", "commodity": "gas", "capacity": "8 bcm/y", "status": "operating",
     "path": [[12.2, 32.87], [13.5, 35.0], [14.25, 37.07]]},
    {"id": "dolphin", "name": "Dolphin", "commodity": "gas", "capacity": "20 bcm/y", "status": "disrupted",
     "note": "Qatar's pipeline gas to the UAE and Oman.", "path": [[51.55, 25.9], [53.0, 25.2], [54.7, 24.7], [56.3, 24.2]]},
    {"id": "emg", "name": "Israel → Egypt (EMG / Arab Gas)", "commodity": "gas", "capacity": "≈10 bcm/y",
     "status": "operating", "path": [[34.55, 31.67], [33.8, 31.13], [32.3, 30.6]]},
    {"id": "sur_de_texas", "name": "Sur de Texas–Tuxpan", "commodity": "gas", "capacity": "2.6 Bcf/d",
     "status": "operating", "path": [[-97.2, 25.9], [-96.9, 23.5], [-97.4, 20.95]]},
    {"id": "gasbol", "name": "Gasbol (Bolivia–Brazil)", "commodity": "gas", "capacity": "30 MMcm/d", "status": "operating",
     "path": [[-63.2, -17.8], [-57.7, -19.0], [-52.0, -21.5], [-46.6, -23.5]]},
    {"id": "rompco", "name": "ROMPCO (Mozambique–South Africa)", "commodity": "gas", "capacity": "≈5 bcm/y",
     "status": "operating", "path": [[35.3, -21.7], [32.6, -25.9], [29.2, -26.5]]},
    {"id": "yadana", "name": "Yadana/Yetagun (Myanmar–Thailand)", "commodity": "gas", "capacity": "≈9 bcm/y",
     "status": "operating", "path": [[97.3, 14.9], [98.5, 14.3], [99.8, 13.5]]},
]

LNG_TERMINALS = [
    {"name": "Ras Laffan", "country": "QAT", "coords": [51.55, 25.9], "capacity_mtpa": 77, "status": "disrupted",
     "note": "Force majeure since Mar 2026; two trains damaged."},
    {"name": "Das Island", "country": "ARE", "coords": [52.87, 25.15], "capacity_mtpa": 5.6, "status": "disrupted"},
    {"name": "Sabine Pass", "country": "USA", "coords": [-93.87, 29.73], "capacity_mtpa": 30, "status": "operating"},
    {"name": "Corpus Christi", "country": "USA", "coords": [-97.2, 27.88], "capacity_mtpa": 25, "status": "operating"},
    {"name": "Plaquemines", "country": "USA", "coords": [-89.7, 29.6], "capacity_mtpa": 20, "status": "operating"},
    {"name": "Cameron", "country": "USA", "coords": [-93.33, 30.05], "capacity_mtpa": 13.5, "status": "operating"},
    {"name": "Freeport", "country": "USA", "coords": [-95.3, 28.9], "capacity_mtpa": 15, "status": "operating"},
    {"name": "Calcasieu Pass", "country": "USA", "coords": [-93.33, 29.77], "capacity_mtpa": 10, "status": "operating"},
    {"name": "LNG Canada", "country": "CAN", "coords": [-128.7, 54.0], "capacity_mtpa": 14, "status": "operating"},
    {"name": "Gorgon / Wheatstone", "country": "AUS", "coords": [115.4, -20.8], "capacity_mtpa": 24.5, "status": "operating"},
    {"name": "North West Shelf", "country": "AUS", "coords": [116.8, -20.6], "capacity_mtpa": 16.9, "status": "operating"},
    {"name": "Ichthys", "country": "AUS", "coords": [130.9, -12.5], "capacity_mtpa": 8.9, "status": "operating"},
    {"name": "Gladstone (QCLNG/APLNG/GLNG)", "country": "AUS", "coords": [151.3, -23.8], "capacity_mtpa": 25.3, "status": "operating"},
    {"name": "Yamal LNG", "country": "RUS", "coords": [72.1, 71.3], "capacity_mtpa": 17.4, "status": "operating"},
    {"name": "Sakhalin-2", "country": "RUS", "coords": [142.9, 46.6], "capacity_mtpa": 9.6, "status": "operating"},
    {"name": "Bintulu", "country": "MYS", "coords": [113.1, 3.3], "capacity_mtpa": 30, "status": "operating"},
    {"name": "Bontang", "country": "IDN", "coords": [117.5, 0.1], "capacity_mtpa": 11.5, "status": "operating"},
    {"name": "Tangguh", "country": "IDN", "coords": [133.1, -2.45], "capacity_mtpa": 11.4, "status": "operating"},
    {"name": "PNG LNG", "country": "PNG", "coords": [147.0, -9.6], "capacity_mtpa": 8.3, "status": "operating"},
    {"name": "Nigeria LNG (Bonny)", "country": "NGA", "coords": [7.2, 4.4], "capacity_mtpa": 22, "status": "operating"},
    {"name": "Arzew / Skikda", "country": "DZA", "coords": [-0.3, 35.85], "capacity_mtpa": 25, "status": "operating"},
    {"name": "Qalhat", "country": "OMN", "coords": [59.4, 22.7], "capacity_mtpa": 11.4, "status": "operating",
     "note": "Outside Hormuz — exports continue."},
    {"name": "Hammerfest", "country": "NOR", "coords": [23.6, 70.7], "capacity_mtpa": 4.3, "status": "operating"},
    {"name": "Atlantic LNG", "country": "TTO", "coords": [-61.8, 10.2], "capacity_mtpa": 15, "status": "operating"},
    {"name": "Peru LNG", "country": "PER", "coords": [-76.3, -13.25], "capacity_mtpa": 4.5, "status": "operating"},
    {"name": "Brunei LNG", "country": "BRN", "coords": [114.6, 4.7], "capacity_mtpa": 7.2, "status": "operating"},
    {"name": "Coral Sul FLNG", "country": "MOZ", "coords": [40.7, -10.3], "capacity_mtpa": 3.4, "status": "operating"},
    {"name": "Greater Tortue Ahmeyim FLNG", "country": "SEN", "coords": [-16.9, 16.0], "capacity_mtpa": 2.5, "status": "operating"},
    {"name": "Angola LNG", "country": "AGO", "coords": [12.3, -6.1], "capacity_mtpa": 5.2, "status": "operating"},
    {"name": "Idku", "country": "EGY", "coords": [30.3, 31.3], "capacity_mtpa": 7.2, "status": "operating"},
]
